### ISSUE TITLE
String reference not set to an instance of a String.

### ISSUE THREAD

**Issue by pspunk** [RupertAvery/PSXPackager#8] opened 2021-01-05 06:30 UTC
Hello, I found this to try instead of psx2psp. I am trying to convert the newly released title 'Magic Castle' to PBP format. Following your readme I have input the correct command but I do not get any output file.  

> PS D:\Backup\SONY\PSP\PSX2PSPv1.4.2> .\psxpackager -i T:\Downloads2T\Magic_Castle_2020_23_dec.zip [-o D:\Backup\SONY\PSP\PSX2PSPv1.4.2\Newfolder] [-l 0] [-y]
> PSXPackager v1.4 by RupertAvery
> 
> Input : T:\Downloads2T\Magic_Castle_2020_23_dec.zip
> Output: T:\Downloads2T
> Compression Level: 5
> 
> Processing started: 01:25:36
> Processing T:\Downloads2T\Magic_Castle_2020_23_dec.zip
> Decompressing file Magic_Castle_2020_23_dec.cue -
> Decompressing file Magic_Castle_2020_23_dec.bin - 100%
> Using Title 'Magic_Castle_2020_23_dec'
> Writing T:\Downloads2T\Magic_Castle_2020_23_dec.PBP...
> 
> String reference not set to an instance of a String.
> Parameter name: s
> Processing completed: 00h 00m 02s

**Comment by RupertAvery** [comment] 2021-01-06 08:07
Maybe don't put square brackets around the options. The square brackets in the argument declarations are to signify that they are optional, at least, that's what they did in DOS days.

**Comment by pspunk** [comment] 2021-01-06 08:21
Thank you for your reply. Removing the brackets give a new error:  
  

> PS D:\Backup\SONY\PSP\PSX2PSPv1.4.2> .\psxpackager -i T:\Downloads2T\Magic_Castle_2020_23_dec.zip -o D:\Backup\SONY\PSP\PSX2PSPv1.4.2\Newfolder -l 0 -y
PSXPackager 1.4.0
Copyright (C) 2021 RupertAvery

ERROR(S):
  Option 'y' is unknown.


After removing the -y argument I still end up with the initial problem.

**Comment by RupertAvery** [comment] 2021-01-06 09:47
It was caused by an empty GameID. I thought I had fixed it but of course I hadn't tested it.  MagicCastle doesn't have a GameID since it is an unofficial release. I use GameIDs to set some fields in the PBP, and I was generating a dummy GameID, but I didn't realize I was using the still-empty ScannerID field.

It's fixed now, Magic Castle is converted to a PBP

Please get the latest release:

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.4.1

**Closed** 2021-01-06 09:47 UTC
